header_include_path: voronoi_planner/voronoi_planner.hpp
namespace: VoronoiPlanner
node_class_name: VoronoiPlannerNode

params:
  distance_tresh:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Distance threshold in class Triangle."
    constraints: "Can be changed."
    read_only: false
    var_name: distance_tresh_

  plot_voronoi:
    type: bool
    default_value: false
    description: "Plot Voronoi diagram."
    constraints: "Cannot be changed."
    read_only: true
    var_name: plot_voronoi_

  point_distance:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Point distance in class Line."
    constraints: "Can be changed."
    read_only: false
    var_name: point_distance_

  rdp_epsilon:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "RDP epsilon in class GeneralizedVoronoi."
    constraints: "Can be changed."
    read_only: false
    var_name: rdp_epsilon_

  save_log:
    type: bool
    default_value: false
    description: "Save log."
    constraints: "Cannot be changed."
    read_only: true
    var_name: save_log_
