header_include_path: voronoi_planner/voronoi_planner.hpp
namespace: VoronoiPlanner
node_class_name: VoronoiPlannerNode

params:
  distance_tresh:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Distance threshold in class Triangle."
    constraints: "Can be changed."
    read_only: false
    var_name: distance_tresh_

  grid_resolution:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 10.0
    step: 0.0
    description: "Grid resolution."
    constraints: "In meters. Can be changed."
    read_only: false
    var_name: grid_resolution_

  field_size:
    type: double_array
    default_value: [0.0]
    min_value: -100.0
    max_value: 100.0
    step: 0.0
    description: "Field size."
    constraints: "In meters. Cannot be changed."
    read_only: true
    var_name: field_size_

  line_increase:
    type: double
    default_value: 0.0
    min_value: -3.0
    max_value: 3.0
    step: 0.0
    description: "Coefficient for line increase."
    constraints: "In meters. Can be changed."
    read_only: false
    var_name: line_increase_

  max_acc:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100.0
    step: 0.0
    description: "Maximum acceleration module."
    constraints: "In meters/second^2. Cannot be changed."
    read_only: true
    var_name: max_acc_

  max_vel:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 10.0
    step: 0.0
    description: "Maximum velocity module."
    constraints: "In meters/second. Cannot be changed."
    read_only: true
    var_name: max_vel_

  move_coefficient:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Coefficient for A* nodes translation."
    constraints: "Can be changed."
    read_only: false
    var_name: move_coefficient_

  plot_size:
    type: integer_array
    default_value: [0]
    min_value: 0
    max_value: 10000
    step: 1
    description: "Plot size."
    constraints: "Can be changed."
    read_only: false
    var_name: plot_size_

  plot_voronoi:
    type: bool
    default_value: false
    description: "Plot Voronoi diagram."
    constraints: "Cannot be changed."
    read_only: true
    var_name: plot_voronoi_

  point_distance:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Point distance in class Line."
    constraints: "Can be changed."
    read_only: false
    var_name: point_distance_

  robot_goal:
    type: double_array
    default_value: [0.0]
    min_value: -100.0
    max_value: 100.0
    step: 0.0
    description: "Robot goal position."
    constraints: "Can be changed."
    read_only: false
    var_name: robot_goal_

  robot_start:
    type: double_array
    default_value: [0.0]
    min_value: -100.0
    max_value: 100.0
    step: 0.0
    description: "Robot start position."
    constraints: "Can be changed."
    read_only: false
    var_name: robot_start_

  rdp_epsilon:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "RDP epsilon in class GeneralizedVoronoi."
    constraints: "Can be changed."
    read_only: false
    var_name: rdp_epsilon_

  points_tresh:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Threshold to filter out points after A*."
    constraints: "Can be changed."
    read_only: false
    var_name: points_tresh_

  sample_points:
    type: integer
    default_value: 0
    min_value: 0
    max_value: 100000
    step: 1
    description: "Number of points to sample."
    constraints: "Can be changed."
    read_only: false
    var_name: sample_points_

  save_log:
    type: bool
    default_value: false
    description: "Save log."
    constraints: "Cannot be changed."
    read_only: true
    var_name: save_log_

  spline_bc_order:
    type: integer
    default_value: 1
    min_value: 1
    max_value: 2
    step: 1
    description: "Boundary condition order for spline."
    constraints: "Can be changed."
    read_only: false
    var_name: spline_bc_order_

  spline_bc_values:
    type: double_array
    default_value: [0.0]
    min_value: -1000.0
    max_value: 1000.0
    step: 0.0
    description: "Boundary condition values for spline."
    constraints: "Can be changed."
    read_only: false
    var_name: spline_bc_values_
