header_include_path: voronoi_planner/voronoi_planner.hpp
namespace: VoronoiPlanner
node_class_name: VoronoiPlannerNode

params:
  distance_tresh:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Distance threshold in class Triangle."
    constraints: "Can be changed."
    read_only: false
    var_name: distance_tresh_

  move_coefficient:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Coefficient for A* nodes translation."
    constraints: "Can be changed."
    read_only: false
    var_name: move_coefficient_

  plot_voronoi:
    type: bool
    default_value: false
    description: "Plot Voronoi diagram."
    constraints: "Cannot be changed."
    read_only: true
    var_name: plot_voronoi_

  point_distance:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Point distance in class Line."
    constraints: "Can be changed."
    read_only: false
    var_name: point_distance_

  rdp_epsilon:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "RDP epsilon in class GeneralizedVoronoi."
    constraints: "Can be changed."
    read_only: false
    var_name: rdp_epsilon_

  points_tresh:
    type: double
    default_value: 0.0
    min_value: 0.0
    max_value: 100000
    step: 0.0
    description: "Threshold to filter out points after A*."
    constraints: "Can be changed."
    read_only: false
    var_name: points_tresh_

  sample_points:
    type: integer
    default_value: 0
    min_value: 0
    max_value: 100000
    step: 1
    description: "Number of points to sample."
    constraints: "Can be changed."
    read_only: false
    var_name: sample_points_

  save_log:
    type: bool
    default_value: false
    description: "Save log."
    constraints: "Cannot be changed."
    read_only: true
    var_name: save_log_

  spline_bc_order:
    type: integer
    default_value: 1
    min_value: 1
    max_value: 2
    step: 1
    description: "Boundary condition order for spline."
    constraints: "Can be changed."
    read_only: false
    var_name: spline_bc_order_

  spline_bc_values:
    type: double_array
    default_value: [0.0]
    min_value: -1000.0
    max_value: 1000.0
    step: 0.0
    description: "Boundary condition values for spline."
    constraints: "Can be changed."
    read_only: false
    var_name: spline_bc_values_
