/object_detector:
  ros__parameters:
    autostart: true
    best_effort_sub_qos: true
    image_dims: [640, 480]
    image_sub_depth: 1
    input_topic: /usb_camera/usb_camera_driver/camera/image_color
    model_score_threshold: 0.45
    model_NMS_threshold: 0.50
    onnx_path: /home/neo/workspace/tools/yolov10/examples/YOLOv8-CPP-Inference/build/yolov8s.onnx
    output_topic: /targets
    stream_topic: /targets_stream
    transport: raw
    use_gpu: true
    visual_data_topic: /targets_visual
    worker_cpu: -1
