/voronoi_planner:
  ros__parameters:
    distance_tresh: 0.15
    field_size: [20.0, 10.0]
    grid_resolution: 0.2
    line_increase: 0.1
    max_acc: 1.0
    max_vel: 1.0
    move_coefficient: 0.15
    plot_voronoi: false
    plot_size: [1500, 800]
    point_distance: 0.2
    points_tresh: 0.4
    rdp_epsilon: 0.064
    robot_goal: [19.5, 0.3]
    robot_start: [2.0, 5.5]
    sample_points: 100
    save_log: false
    spline_bc_order: 2
    spline_bc_values: [0.0, 0.0, 0.0]